### ISSUE TITLE
'junior' repositories required to generate 'senior'

### ISSUE THREAD

**Issue by ewillink** [eclipse-justj/justj.tools#2]
While migrating to JustJ, testing may execute in unusual orders. Thus

If a 'release' generation of org.eclipse.justj.p2.manager is requested before a 'milestone' or 'nightly' an ISE results.

`Caused by: org.eclipse.equinox.p2.core.ProvisionException: No repository found at file:/C:/Temp/project.build.directory/qvto-sync/justj-tooling/updates/milestone/latest.
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.fail(AbstractRepositoryManager.java:409)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:674)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.justj.p2.UpdateSiteGenerator$RepositoryAnalyzer.getMetadataRepository(UpdateSiteGenerator.java:2227)
	... 17 more
`
Workaround: build 'nightly' then 'milestone' then 'release'

**Comment by merks** [comment]
Use nightly bukld.  At this point in time, I do not want to manage milestones and release.

**Comment by merks** [comment]
Oh, I misread your comment. 

 But yes, as described:

> release - This will not promote the newly built site as a release build. Instead it will promote (mirror) the latest milestone build as a release build. I.e., the release update site will contain byte-for-byte the same artfiacts as the latest milestone. The folder name will be of the form x.y.z where the -version-iu or -version-iu-pattern determines the version. 

So yes, there must be milestone to promote to a release in order to do a release build.

**Comment by ewillink** [comment]
No. Bulding a 'milestone' buiild without a prior 'nightly' has the problem too. My guess is that the ISE coiuld be caught/not thrown and the processing for the 'missing' build-type skipped/warned. (Certainly a near trivial issue since there is an easy workaropund; just liable to catch out newbies who may fail to diagnose the trivial cause/solution quickly.)

**Comment by merks** [comment]
It's documented now.
